name: build

on:
  push:
  schedule:
    - cron: '23 1 * * SUN'

jobs:
  data:
    defaults:
      run:
        working-directory: jinhe_data
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/provision-with-micromamba@v11
        with:
          environment-file: "jinhe_data/environment.yml"
      - run: docker-compose up -d
      - run: sleep 3
      - run: python -m src.main
      - run: "docker cp redisgraph:/data/dump.rdb ."
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: CCXXXI/jinhe-bus-routes-server/data
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          default_branch: main
          workdir: jinhe_data
          cache: ${{ github.event_name != 'schedule' }}
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: CCXXXI/jinhe-bus-routes-server/server
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          default_branch: main
          workdir: jinhe_server
          cache: ${{ github.event_name != 'schedule' }}
