name: build

on: [push]

jobs:
  data:
    defaults:
      run:
        working-directory: jinhe_data
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/provision-with-micromamba@v11
        with:
          environment-file: "jinhe_data/environment.yml"
      - run: docker-compose up -d
      - run: python -m src.main
      - run: "docker cp redisgraph:/data/dump.rdb ."
      # todo
      - run: ls
