name: check

on:
  push:
  pull_request:
  schedule:
    - cron: "44 13 * * SUN"

jobs:
  data:
    defaults:
      run:
        working-directory: jinhe_data
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/provision-with-micromamba@v11
        with:
          environment-file: "jinhe_data/environment.yml"
      - run: docker-compose up -d
      - run: sleep 3
      - run: pytest --cov=./ --cov-report xml
      - uses: codecov/codecov-action@v2
  server:
    defaults:
      run:
        working-directory: jinhe_server
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/provision-with-micromamba@v11
        with:
          environment-file: "jinhe_server/dev.environment.yml"
      - run: docker-compose up -d
      - run: sleep 3
      - run: pytest --cov=./ --cov-report xml
      - uses: codecov/codecov-action@v2
